include:
  - compose.monitoring.yml
services:
  frontend:
    build:
      context: ./frontend
    env_file:
      - frontend/.env
    depends_on:
      - backend
    ports:
      - "5173:5173"
    networks:
      - frontend-network

  backend:
    build:
      context: ./backend
    env_file:
      - backend/.env
    netowrks:
      - frontend-network
      - backend-network
    depends_on:
      - db

    db:
      image: postgres:13
      environment:
        POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
        POSTGRES_USER: app
        POSTGRES_DB: app
      secrets:
        - postgres_password
      networks:
        - backend-network
      volumes:
        - postgres_data: /var/lib/postgreql/data


    adminer:
      image: adminer
      restart: always
      environment:
        ADMINER_DEFAULT_SERVER: db
      networks:
        - backend-network

    nginx_proxy:
      image: jc21/nginx-proxy-manager:latest
      ports:
        - "80:80"
        - "443:443"
        - "8090:81"
      environment:
        DB_SQLITE_FILE: "/data/database.sqlite"
      volumes:
        - data:/data
        - letsencrypt:/etc/letsencrypt
       # - ./nginx/nginx.dev.conf:/data/nginx/custom/http_top.conf
      restart: always
      depends_on:
        - frontend
        - backend
        - adminer
        - prometheus
        - grafana
      networks:
        - frontend-network
        - backend-network

networks:
  frontend-network
  backend-network
volumes:
  postgres_data:
  data:
  letsencrypt:

secrets:
  postgres_password:
    file: ./POSTGRES_PASSWORD.txt
